### PR TITLE
Fixed Navbar

### LINKED ISSUE #27: Add Dropdown to profile menu
Fixed the Navbar to feature profile icon that shows Profile and Logout Dropdown menu when hovered.

### PR DESCRIPTION
**Pull request by TusharJiShukla**
This PR adds the following enhancements to :

Created Admin Dashboard UI.

Integrated Blog page within the Admin section.

Added a dropdown menu that appears on hovering over the profile icon in the Navbar.

Updated Navbar UI for a smoother user experience.

Linked Issue:
Fixes #27 , #23 and #20

### CODE REVIEW

File: app/AdminDashboard/blogsAdmin/page.tsx [hunk 1]
```diff
@@ -0,0 +1,265 @@
...
+
+const BlogsAdminPage = () => {
+  const [blogs, setBlogs] = useState<Blog[]>([]);
+  const [loading, setLoading] = useState(true);
+  const [paraphraseTexts, setParaphraseTexts] = useState<Record<string, string>>({});
+  const [filter, setFilter] = useState<FilterType>("all");
+
+ useEffect(() => {
+  axios
+    .get("http://localhost:5000/blogs")
```
Comment (sneha-chavan) [inline app/AdminDashboard/blogsAdmin/page.tsx:35]: We can have environment variable here as well

File: app/AdminDashboard/blogsAdmin/page.tsx [hunk 2]
```diff
@@ -0,0 +1,265 @@
...
+    .then((res) => {
+      const sortedBlogs = res.data.sort(
+        (a: Blog, b: Blog) => new Date(b.date).getTime() - new Date(a.date).getTime()
+      );
+      setBlogs(sortedBlogs);
```
Comment (sneha-chavan) [inline app/AdminDashboard/blogsAdmin/page.tsx:40]: error handling is missing

File: app/AdminDashboard/blogsAdmin/page.tsx [hunk 3]
```diff
@@ -0,0 +1,265 @@
...
+    })
+    .finally(() => setLoading(false));
+}, []);
+
+
+  const handleVerify = (id: string) => {
+    axiosInstance.put(`http://localhost:5000/blogs/${id}`, { verified: true }).then(() => {
+      setBlogs((prev) =>
```
Comment (sneha-chavan) [inline app/AdminDashboard/blogsAdmin/page.tsx:48]: save into env var

File: app/AdminDashboard/blogsAdmin/page.tsx [hunk 4]
```diff
@@ -0,0 +1,265 @@
...
+        prev.map((b) => (b._id === id ? { ...b, verified: true } : b))
+      );
+    });
+  };
+
+  const handleDelete = (id: string) => {
+    if (!confirm("Are you sure you want to delete this blog?")) return;
+    axiosInstance.delete(`http://localhost:5000/blogs/${id}`).then(() => {
```
Comment (sneha-chavan) [inline app/AdminDashboard/blogsAdmin/page.tsx:56]: same

File: app/AdminDashboard/blogsAdmin/page.tsx [hunk 5]
```diff
@@ -0,0 +1,265 @@
...
+      case "notParaphrased":
+        return !blog.paraphrased;
+      default:
+        return true; // all
+    }
+  });
+
+  if (loading)
+    return (
+      <div className="p-6 max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
```
Comment (sneha-chavan) [inline app/AdminDashboard/blogsAdmin/page.tsx:98]: we can create a separate loading component

File: app/AdminDashboard/blogsAdmin/page.tsx [hunk 6]
```diff
@@ -0,0 +1,265 @@
...
+                : "bg-gray-200 text-gray-700 hover:bg-gray-300"
+            }`}
+          >
+            {label}
+          </button>
+        ))}
+      </div>
+
+      {/* Blogs Grid */}
+      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
```
Comment (sneha-chavan) [inline app/AdminDashboard/blogsAdmin/page.tsx:135]: we should create separate component for Blogs Grid

**Review by sneha-chavan — CHANGES_REQUESTED** [review]
